<?php

namespace App\Admin\Sections;

use App\Terminal;
use Zeus\Admin\Cms\Sections\ZeusAdminPosts;
use Zeus\Admin\SectionBuilder\Form\Panel\Fields\BaseField\FormField;

class News extends ZeusAdminPosts
{
    protected $title = 'Новости';
    protected $model = 'App\\CmsBoosterPost';

    public static function onEdit($id)
    {
        $form = parent::onEdit($id); // TODO: Change the autogenerated stub

        $leftColumn = $form->getColumns()[0];
        $leftColumnFields = $leftColumn->getFields();
        $newFields = [
            FormField::bselect('terminals', 'Терминалы')
                ->setDataAttributes([
                    'multiple', 'data-live-search="true"'
                ])
                ->setModelForOptions(Terminal::class)
                ->setDisplay('name_with_city')
        ];

        array_splice(
            $leftColumnFields,
            6,
            0,
            $newFields
        );

        $leftColumn->setFields($leftColumnFields);

        $rightColumn = $form->getColumns()[1];
        $rightColumnFields = $rightColumn->getFields();
        $rightColumnFields['99.99'] = FormField::hidden('type')->setValue('news');
        $rightColumn->setFields($rightColumnFields);

        $form->setColumns([
            $leftColumn,
            $rightColumn
        ]);

        return $form;
    }

    public static function onCreate()
    {
        return self::onEdit(null);
    }
}